
[[constraint]]
  name = "github.com/golang/protobuf"
  version = "1.1.0"

[[constraint]]
  name = "github.com/joho/godotenv"
  version = "1.2.0"

[[constraint]]
  name = "github.com/kelseyhightower/envconfig"
  version = "1.3.0"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  name = "go.uber.org/zap"
  version = "1.8.0"

[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.9.8"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.9.8"

[[constraint]]
  name = "k8s.io/client-go"
  version = "~6.0"

[[constraint]]
  name = "k8s.io/helm"
  version = "~2.8"

[prune]
  go-tests = true
  unused-packages = true
